spring.application.name=payment-service

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=
spring.datasource.password=

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml